language: csharp

addons:
  apt:
    packages:
       - msbuild

sudo: false # use the new container-based Travis infrastructure
dist: xenial # Ubuntu 14.04
mono: latest
dotnet: 2.1.400

script:
  - dotnet --info
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - ./build.sh Default