language: csharp

addons:
  apt:
    packages:
       - msbuild

sudo: false
dist: xenial
mono: latest
dotnet: 2.2.103

script:
  - dotnet --info
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.5/
  - ./build.sh Default
